### ISSUE TITLE
Error - static method

### ISSUE THREAD

**Issue by MihaiCtinescu** [devloopsnet/nova-system-settings#1]
Hi, 
i installed you and i received this error:

Cannot make static method Devloops\NovaSystemSettings\Contracts\SystemSettings::title() non static in class

<img width="1381" alt="image" src="https://github.com/devloopsnet/nova-system-settings/assets/124136876/237baef2-5d64-4ea2-b6dd-cd7e01741069">

I tried to fix the issue, but this leads to multiple inserts for declared fields 

<img width="1376" alt="image" src="https://github.com/devloopsnet/nova-system-settings/assets/124136876/db615277-052e-478e-847a-f95009f2cfec">

Thanks,
Mihai

**Comment by AbdullahFaqeir** [comment]
Hi @MihaiCtinescu!

I've updated the readme, please refer to it and make sure to update your package.
